[package]
name = "dioxico"
version = "0.1.0"
license = "MIT"
description = "A collection of UI components for Dioxus."
readme = "../README.md"
repository = "https://github.com/WKHAllen/dioxico"
keywords = ["ui", "web", "wasm", "dioxus", "component"]
categories = ["gui", "web-programming", "wasm"]
edition = "2024"

[dependencies]
csscolorparser = "0.8"
dioxico-macros = { path = "../dioxico-macros" }
dioxus = "0.7"
rand = "0.10"

[features]
web = ["dioxus/web"]
desktop = ["dioxus/desktop"]
mobile = ["dioxus/mobile"]

[target.'cfg(target_arch = "wasm32")'.dependencies]
getrandom = { version = "0.4", features = ["wasm_js"] }
wasmtimer = "0.4"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
tokio = { version = "1", features = ["time"] }

[dev-dependencies]
convert_case = "0.11"

[target.'cfg(target_arch = "wasm32")'.dev-dependencies]
dioxus = { version = "0.7", features = ["web"] }

[target.'cfg(not(target_arch = "wasm32"))'.dev-dependencies]
dioxus = { version = "0.7", features = ["desktop"] }
