[package]
name = "dioxico-macros"
version = "0.1.0"
license = "MIT"
description = "A collection of UI components for Dioxus."
readme = "../README.md"
repository = "https://github.com/WKHAllen/dioxico"
keywords = ["ui", "web", "wasm", "dioxus", "component"]
categories = ["gui", "web-programming", "wasm"]
edition = "2024"

[lib]
proc-macro = true

[dependencies]
convert_case = "0.11"
proc-macro-crate = "3.5"
proc-macro2 = "1.0"
quote = "1.0"
syn = "2.0"
